package jsonParser;

public enum TokenKind {
    LEFT_BRACE, RIGHT_BRACE, LEFT_BRACKET, RIGHT_BRACKET,
    COLON, COMMA, EOF,
    LITERAL_STRING, LITERAL_NUMBER, LITERAL_TRUE, LITERAL_FALSE, LITERAL_NULL
}
